name: Benchmark and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # === Build Benchmark Server ===
      - name: Setup Benchmark Server
        run: |
          cd server
          npm install
          npm run build
          npm run gen
          mkdir -p reports
      
      # === Build Puppeteer

      - name: Build Puppeteer
        run: |
          cd benchmark
          npm install
          npm run build

      - name: Benchmark React
        run: |
          cd react
          
          npm install
          npm i -g serve
          
          npm run build
          serve -s build &
          
          cd ../server
          npm run start react &
          
          sleep 30
          
          cd ../benchmark
          npm run start http://localhost:3000/

      # === Angular Benchmark ===
      - name: Benchmark Angular
        run: |
          cd angular

          npm install
          npm run performance
          
          cd ../server
          npm run start angular &
          
          sleep 20
          
          cd ../benchmark
          npm run start http://localhost:4200/

      # === Svelte Benchmark ===
      - name: Benchmark Svelte
        run: |
          cd svelte

          npm install
          npm run build
          npm run preview &
          
          cd ../server
          npm run start svelte &
          
          sleep 20
          npm run start http://localhost:4173/

      - name: Benchmark Vanilla JS
        run: |
          cd ../server
          npm run start js &
          sleep 20
          cd ..
          npm run  start ./vanila/index.html

      # all at once
      - name: Save Reports
        run: |
          mkdir -p public/reports
          mv server/reports/*.html public/reports/
          mv server/reports/*.csv public/reports/

      # === Dashboard & Deploy ===
      - name: Copy Dashboard HTML
        run: |
          mkdir -p public
          cp ./server/dashboard.html public/index.html
          cp ./server/dashboard.html index.html

          ls
          ls public
          ls public/reports


      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: benchmark
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
